services:
  agent-runtime:
    build:
      context: .
      dockerfile: ./docker/bedrock_agent_runtime/local.Dockerfile
      platforms:
        - linux/arm64
    container_name: agent-runtime-dev
    ports:
      - "8080:8080"
    environment:
      AWS_PROFILE: ykoba
      AWS_REGION: ap-northeast-1
      KNOWLEDGE_BASE_ID: "WARIASYSZC"
      DATA_SOURCE_ID: "NBNBVECKHM"
      BEDROCK_MODEL_ARN: "arn:aws:bedrock:ap-northeast-1:795090432220:inference-profile/jp.anthropic.claude-sonnet-4-5-20250929-v1:0"
      PORT: 8080
      GIN_MODE: debug
    volumes:
      - .:/app
      - ${HOME}/.aws:/root/.aws:ro
    restart: unless-stopped
