services:
  agent-runtime:
    build:
      context: .
      dockerfile: ./docker/bedrock_agent_runtime/local.Dockerfile
      platforms:
        - linux/arm64
    container_name: agent-runtime-dev
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: ap-northeast-1
      KNOWLEDGE_BASE_ID: "WARIASYSZC"
      DATA_SOURCE_ID: "NBNBVECKHM"
      PORT: 8080
      GIN_MODE: debug
    volumes:
      - .:/app
      - ${HOME}/.aws:/root/.aws:ro

    # 再起動は任意
    restart: unless-stopped
