services:
  agent-runtime:
    build:
      context: .
      dockerfile: ./docker/bedrock_agent_runtime/local.Dockerfile
      platforms:
        - linux/arm64
    container_name: agent-runtime-dev
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: ap-northeast-1
      KNOWLEDGE_BASE_ID: "todo: set your knowledge base id"
      DATA_SOURCE_ID: "todo"
      KNOWLEDGE_S3_BUCKET: "todo-your-bucket-name"
      KNOWLEDGE_S3_PREFIX: "todo/knowledge-base/"
      PORT: 8080
      GIN_MODE: debug
    volumes:
      - .:/app
      - ${HOME}/.aws:/root/.aws:ro

    # 再起動は任意
    restart: unless-stopped
